# Generated by Django 4.1.5 on 2023-01-31 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerbook',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='customerbook',
            name='is_deleted',
        ),
    ]
